name: beaver_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - humanfriendly==10.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.2.6
      - onnx==1.19.1
      - onnxruntime==1.23.2
      - onnxslim==0.1.82
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==12.0.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - protobuf==6.33.4
      - psutil==7.1.3
      - pyarmor==9.2.3
      - pyarmor-cli-core==8.1.0
      - pyparsing==3.2.5
      - pyreadline3==3.5.4
      - pyside6==6.10.1
      - pyside6-addons==6.10.1
      - pyside6-essentials==6.10.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.16.3
      - shiboken6==6.10.1
      - six==1.17.0
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
      - typing-extensions==4.15.0
      - ultralytics==8.3.237
      - ultralytics-thop==2.0.18
      - urllib3==2.6.2
prefix: C:\Users\davidthien\miniconda3\envs\beaver_env
